# Modeling

### Getting encoded data

Since we have to do feature selection again we have to do one hot encoding again

In [1]:
import pandas as pd
import numpy as np

In [2]:
cleaned_df = pd.read_csv("cleaned_df.csv") 

In [12]:
list(cleaned_df.columns)

['Unnamed: 0',
 'ARM',
 'HR1_10SCALE',
 'HR2_1',
 'HR2_2',
 'HR2_3',
 'HR2_4',
 'HR2_5',
 'HR3',
 'HR4',
 'HR5',
 'HR6',
 'HR7_1',
 'HR7_2',
 'HR7_3',
 'HR7_4',
 'HR8',
 'HR11',
 'HR12_1',
 'HR12_2',
 'HR12_3',
 'HR12_4',
 'HR12_5',
 'HR13',
 'HR14',
 'COVID_HR3',
 'STIMULUS2',
 'STIMULUS3',
 'STIMULUS4',
 'STIMULUS5',
 'STIMULUS6',
 'POLICY1',
 'POLICY2',
 'POLICY3',
 'POLICY4',
 'PERSONAL2',
 'PERSONAL3',
 'PERSONAL4',
 'WORRY_1',
 'WORRY_2',
 'WORRY_3',
 'WORRY_4',
 'WORRY_5',
 'WORRY_6',
 'WORRY_7',
 'WORRY_8',
 'MEDIA1',
 'MEDIA2',
 'MEDIA5',
 'MEDIA6_1',
 'MEDIA6_2',
 'MEDIA6_3',
 'MEDIA6_4',
 'MEDIA6_5',
 'MEDIA6_6',
 'MEDIA6_7',
 'MEDIA7',
 'MEDIA9',
 'MEDIA10',
 'MEDIA11',
 'MEDIA12',
 'MEDIA13',
 'MEDIA14',
 'MEDIA15',
 'MEDIA17',
 'MH1',
 'MH2',
 'CHILDCARE1',
 'CHILDCARE2',
 'CHILDCARE3',
 'ELDERLYCARE1',
 'IDEOLOGY1',
 'IDEOLOGY2',
 'IDEOLOGY3',
 'IDEOLOGY5',
 'IDEOLOGY6',
 'IDEOLOGY7',
 'IDEOLOGY8',
 'CULTURE1_1',
 'CULTURE1_2',
 'CULTURE1_3',
 'CULTURE1_4',
 'CULTURE1_5'

In [3]:
cleaned_df = cleaned_df.drop(["COVID_HR1","COVID_HR2","IDEOLOGY4"],axis=1)
missing = ["HR11","IDEOLOGY7"]
for i in missing:
    mode = cleaned_df[i].mode()
    print(mode[0])
    fixed = []
    for value in cleaned_df[i]:
        if value == 'NA' or value != value:
            fixed.append(mode[0])
        else:
            fixed.append(value)
    cleaned_df[i] = fixed

B
C


In [4]:
for (columnName, columnData) in cleaned_df.iteritems(): 
    missingCount = (columnData == 'NA').sum() 
    missingCount += columnData.isnull().sum() 
    percentage = (missingCount/len(cleaned_df))*100 
    #print(percentage)
    if missingCount > 0:        
        print("Missing Values in column : ", columnName, ", missing rows: ", 
            missingCount, ", missing percentage: ",  percentage, '%') 
        if percentage > 50.0:
            too_many_missing_value_columns.append(columnName) 

### Feature selection
Feature we are going to use here is the ordinal IDEOLOGY5. IDEOLOGY5 is "If you had to describe your ideology along a Left-Right political spectrum, which of the following would come closest to how you would describe yourself?"

In [7]:
cleaned_df["IDEOLOGY5"].unique()

array([ 2,  0, -2, -1,  1], dtype=int64)

In [8]:
tmp_df = cleaned_df.copy()
nominal_val = cleaned_df.select_dtypes(include=['object']).columns
for index, values in tmp_df.iteritems():
    if index in nominal_val:
        unique = pd.unique(values)
        dic = []
        for i in values:
            print(np.where(unique == i))
            print(index)
            dic.append(np.where(unique == i)[0][0])
        tmp_df[index] = dic

(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([

(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([3], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([0], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([2], dtype=int64),)
HR11
(array([1], dtype=int64),)
HR11
(array([

(array([4], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([2], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([5], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([3], dtype=int64),)
HR13
(array([0], dtype=int64),)
HR13
(array([1], dtype=int64),)
HR13
(array([

HR14
(array([1], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([0], dtype=int64),)
HR14
(array([1], dtype=int64),)
HR14
(array([1], dtype=int64),)
HR14
(array([1], dtype=int64),)
HR14
(array([4], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([4], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([5], dtype=int64),)
HR14
(array([1], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([4], dtype=int64),)
HR14
(array([4], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([4], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([2], dtype=int64),)
HR14
(array([1], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([4], dtype=int64),)
HR14
(array([1], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(array([3], dtype=int64),)
HR14
(ar

COVID_HR3
(array([2], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([2], dtype=int64),)
COVID_HR3
(array([2], dtype=int64),)
COVID_HR3
(array([2], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([1], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([2], dtype=int64),)
COVID_HR3
(array([2], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([1], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([1], dtype=int64),)
COVID_HR3
(array([0], dtype=int64),)
COVID_HR3
(array([1], dtype=int64),)
C

(array([2], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([2], dtype=int64),)
STIMULUS2
(array([2], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([2], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([2], dtype=int64),)
STIMULUS2
(array([2], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([2], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(array([1], dtype=int64),)
STIMULUS2
(array([0], dtype=int64),)
STIMULUS2
(

(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([4], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([3], dtype=int64),)
STIMULUS5
(array([4], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(

STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([4], dtype=int64),)
STIMULUS5
(array([3], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([5], dtype=int64),)
STIMULUS5
(array([4], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([4], dtype=int64),)
STIMULUS5
(array([2], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([3], dtype=int64),)
STIMULUS5
(array([4], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([1], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
STIMULUS5
(array([0], dtype=int64),)
S

STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([2], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([1], dtype=int64),)
STIMULUS6
(array([1], dtype=int64),)
STIMULUS6
(array([4], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([1], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([2], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([2], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([2], dtype=int64),)
STIMULUS6
(array([2], dtype=int64),)
STIMULUS6
(array([1], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
STIMULUS6
(array([0], dtype=int64),)
STIMULUS6
(array([3], dtype=int64),)
S

POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([1], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([2], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([1], dtype=int64),)
POLICY3
(array([1], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], dtype=int64),)
POLICY3
(array([0], 

POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([0], dtype=int64),)
POLICY4
(array([1], dtype=int64),)
POLICY4
(array([1], 

MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([1], dtype=int64),)
MEDIA2
(array([1], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([1], dtype=int64),)
MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([2], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([3], dtype=int64),)
MEDIA2
(array([0], dtype=int64),)
MEDIA2
(array(

(array([2], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([5], dtype=int64),)
MEDIA5
(array([5], dtype=int64),)
MEDIA5
(array([1], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([1], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([4], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([4], dtype=int64),)
MEDIA5
(array([4], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([0], dt

(array([3], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([1], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([3], dtype=int64),)
MEDIA5
(array([1], dtype=int64),)
MEDIA5
(array([4], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([5], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([0], dtype=int64),)
MEDIA5
(array([4], dtype=int64),)
MEDIA5
(array([2], dtype=int64),)
MEDIA5
(array([0], dt

MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([2], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([0], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array([1], dtype=int64),)
MEDIA9
(array(

(array([1], dtype=int64),)
MEDIA13
(array([0], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([2], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([2], dtype=int64),)
MEDIA13
(array([2], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([2], dtype=int64),)
MEDIA13
(array([0], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([0], dtype=int64),)
MEDIA13
(array([1], dtype=int64),)
MEDIA13
(array([1], dtype=in

(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=in

(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([0], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=int64),)
MEDIA14
(array([1], dtype=in

MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([0], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([0], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([0], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([0], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([0], dtype=int64),)
MEDIA15
(array([1], dtype=int64),)
MEDIA15
(array([1], 

(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=int64),)
MEDIA17
(array([1], dtype=int64),)
MEDIA17
(array([0], dtype=in

CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([1], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(array([0], dtype=int64),)
CHILDCARE1
(

CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(

(array([1], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([1], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([2], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE2
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], 

CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([1], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(array([0], dtype=int64),)
CHILDCARE3
(

ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)
ELDERLYCARE1
(array([0], dtype=int64),)
ELDERLYCARE1
(array([1], dtype=int64),)


(array([1], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([0], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([0], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([0], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([1], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(array([2], dtype=int64),)
IDEOLOGY1
(

(array([0], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([4], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([5], dtype=int64),)
IDEOLOGY2
(array([2], dtype=int64),)
IDEOLOGY2
(array([0], dtype=int64),)
IDEOLOGY2
(array([4], dtype=int64),)
IDEOLOGY2
(array([1], dtype=int64),)
IDEOLOGY2
(

IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([2], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([2], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([2], dtype=int64),)
IDEOLOGY3
(array([2], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([2], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([0], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([1], dtype=int64),)
IDEOLOGY3
(array([2], dtype=int64),)
I

(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([3], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([2], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(

(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([3], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([3], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([2], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([5], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([3], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([1], dtype=int64),)
IDEOLOGY7
(array([0], dtype=int64),)
IDEOLOGY7
(array([3], dtype=int64),)
IDEOLOGY7
(array([4], dtype=int64),)
IDEOLOGY7
(

IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([5], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([2], dtype=int64),)
IDEOLOGY8
(array([2], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([1], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([5], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
IDEOLOGY8
(array([0], dtype=int64),)
IDEOLOGY8
(array([3], dtype=int64),)
I

RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([2], dtype=int64),)
RUMORS2
(array([1], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([3], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([3], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([2], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([1], 

RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([1], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([6], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([2], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([6], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([3], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([4], dtype=int64),)
RUMORS2
(array([2], dtype=int64),)
RUMORS2
(array([6], dtype=int64),)
RUMORS2
(array([0], dtype=int64),)
RUMORS2
(array([1], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([5], dtype=int64),)
RUMORS2
(array([3], dtype=int64),)
RUMORS2
(array([0], 

(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([1], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2
(array([0], dtype=int64),)
DEMOGRAPHIC2


(array([12], dtype=int64),)
DEMOGRAPHIC4
(array([27], dtype=int64),)
DEMOGRAPHIC4
(array([22], dtype=int64),)
DEMOGRAPHIC4
(array([13], dtype=int64),)
DEMOGRAPHIC4
(array([30], dtype=int64),)
DEMOGRAPHIC4
(array([39], dtype=int64),)
DEMOGRAPHIC4
(array([12], dtype=int64),)
DEMOGRAPHIC4
(array([0], dtype=int64),)
DEMOGRAPHIC4
(array([26], dtype=int64),)
DEMOGRAPHIC4
(array([42], dtype=int64),)
DEMOGRAPHIC4
(array([49], dtype=int64),)
DEMOGRAPHIC4
(array([22], dtype=int64),)
DEMOGRAPHIC4
(array([33], dtype=int64),)
DEMOGRAPHIC4
(array([3], dtype=int64),)
DEMOGRAPHIC4
(array([25], dtype=int64),)
DEMOGRAPHIC4
(array([20], dtype=int64),)
DEMOGRAPHIC4
(array([32], dtype=int64),)
DEMOGRAPHIC4
(array([12], dtype=int64),)
DEMOGRAPHIC4
(array([23], dtype=int64),)
DEMOGRAPHIC4
(array([12], dtype=int64),)
DEMOGRAPHIC4
(array([1], dtype=int64),)
DEMOGRAPHIC4
(array([34], dtype=int64),)
DEMOGRAPHIC4
(array([20], dtype=int64),)
DEMOGRAPHIC4
(array([5], dtype=int64),)
DEMOGRAPHIC4
(array([25], dtype=i

(array([179], dtype=int64),)
DEMOGRAPHIC5
(array([564], dtype=int64),)
DEMOGRAPHIC5
(array([565], dtype=int64),)
DEMOGRAPHIC5
(array([566], dtype=int64),)
DEMOGRAPHIC5
(array([567], dtype=int64),)
DEMOGRAPHIC5
(array([568], dtype=int64),)
DEMOGRAPHIC5
(array([141], dtype=int64),)
DEMOGRAPHIC5
(array([569], dtype=int64),)
DEMOGRAPHIC5
(array([570], dtype=int64),)
DEMOGRAPHIC5
(array([312], dtype=int64),)
DEMOGRAPHIC5
(array([571], dtype=int64),)
DEMOGRAPHIC5
(array([572], dtype=int64),)
DEMOGRAPHIC5
(array([573], dtype=int64),)
DEMOGRAPHIC5
(array([574], dtype=int64),)
DEMOGRAPHIC5
(array([411], dtype=int64),)
DEMOGRAPHIC5
(array([575], dtype=int64),)
DEMOGRAPHIC5
(array([576], dtype=int64),)
DEMOGRAPHIC5
(array([312], dtype=int64),)
DEMOGRAPHIC5
(array([146], dtype=int64),)
DEMOGRAPHIC5
(array([312], dtype=int64),)
DEMOGRAPHIC5
(array([577], dtype=int64),)
DEMOGRAPHIC5
(array([578], dtype=int64),)
DEMOGRAPHIC5
(array([142], dtype=int64),)
DEMOGRAPHIC5
(array([579], dtype=int64),)
DEMOG

(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([1], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6


(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([1], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([1], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6
(array([0], dtype=int64),)
DEMOGRAPHIC6


(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([1], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([1], dtype=int64),)
DEMOGRAPHIC7
(array([1], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7
(array([0], dtype=int64),)
DEMOGRAPHIC7


(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([5], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([8], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([10], dtype=int64),)
DEMOGRAPHIC8
(array([6], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([1], dtype=int64),)
DEMOGRAPHIC8
(array([5], dtype=int64),)
DEMOGRAPHIC8
(array([7], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC8
(array([10], dtype=int64),)
DEMOGRAPHIC8
(array([0], dtype=int64),)
DEMOGRAPHIC

DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([0], dtype=int64),)
DEMOGRAPHIC10
(array([1], dtype=int64),)
DEMOGRAPHIC10
(a

(array([3], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([2], dtype=int64),)
DEMOGRAPHIC12
(array([1], dtype=int64),)
DEMOGRAPHIC12
(array([2], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([1], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([2], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([0], dtype=int64),)
DEMOGRAPHIC12
(array([2], dtyp

In [9]:
tmp_df.columns

Index(['Unnamed: 0', 'ARM', 'HR1_10SCALE', 'HR2_1', 'HR2_2', 'HR2_3', 'HR2_4',
       'HR2_5', 'HR3', 'HR4',
       ...
       'RUMORS1_USARMY_BROUGHT', 'RUMORS1_BAT_TO_HUMANS',
       'RUMORS1_BAT_ANIMAL_HUMANS', 'RUMORS1_WET_MARKET', 'RUMORS1_OTHER',
       'DEMOGRAPHIC1_EMPLOYED', 'DEMOGRAPHIC1_UNEMPLOYED',
       'DEMOGRAPHIC1_RETIRED', 'DEMOGRAPHIC1_STUDENTS', 'DEMOGRAPHIC1_OTHER'],
      dtype='object', length=216)

In [14]:
from sklearn.model_selection import train_test_split
X = tmp_df.drop("IDEOLOGY5",axis=1) #obamacare
y = tmp_df["IDEOLOGY5"]
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = .75, test_size = .25, random_state = 72)

In [15]:
from sklearn.feature_selection import SelectKBest, chi2
fs = SelectKBest(score_func=chi2, k='all')
fs.fit(x_train,y_train)
x_train_fs = fs.transform(x_train)
x_test_fs = fs.transform(x_test)

In [23]:
from matplotlib import pyplot

selected_features = []
for i in range(len(fs.scores_)):
    #print('Feature %s: %f' % (tmp_df.columns[i], fs.scores_[i]))
    if fs.scores_[i] > 100:
        print('Feature %s: %f' % (X.columns[i], fs.scores_[i]))
        selected_features.append(X.columns[i])
selected_features.remove("Unnamed: 0")
selected_features

Feature Unnamed: 0: 275.827388
Feature HR6: 101.234607
Feature MEDIA12: 101.260111
Feature IDEOLOGY6: 103.658266
Feature DEMOGRAPHIC4: 123.817113
Feature DEMOGRAPHIC5: 3800.760048


['HR6', 'MEDIA12', 'IDEOLOGY6', 'DEMOGRAPHIC4', 'DEMOGRAPHIC5']

Selected Features are 'HR6', 'MEDIA12', 'IDEOLOGY6', 'DEMOGRAPHIC4', 'DEMOGRAPHIC5' DEMOGRAPHIC 4 is nominal so it will have to be encoded.

### One Hot

In [70]:
selected_df = cleaned_df[selected_features].copy()
selected_df["IDEOLOGY5"] = cleaned_df["IDEOLOGY5"].copy()
selected_df

HR6  MEDIA12  IDEOLOGY6 DEMOGRAPHIC4 DEMOGRAPHIC5  IDEOLOGY5
0       3        1          2           IN        46825          2
1       2        1          2           CO        81650          0
2       0        0          0           GA        31027          2
3       2        2          3           IL        60609          0
4       4        1          2           MS        39466          0
...   ...      ...        ...          ...          ...        ...
1206    3        0          1           OH        43701         -2
1207    4        1          0           DE        34475          0
1208    2        0          4           IL         6152          2
1209    4        0          0           MD        21740          0
1210    1        0          3           KY        40353          2

[1211 rows x 6 columns]

In [71]:
nominal_df = selected_df[selected_df.select_dtypes(include=['object']).columns]
nominal_df

DEMOGRAPHIC4 DEMOGRAPHIC5
0              IN        46825
1              CO        81650
2              GA        31027
3              IL        60609
4              MS        39466
...           ...          ...
1206           OH        43701
1207           DE        34475
1208           IL         6152
1209           MD        21740
1210           KY        40353

[1211 rows x 2 columns]

In [72]:
nn_df = pd.DataFrame()
for i in nominal_df.columns:
    unique = pd.unique(selected_df[i].copy())
    count = 0
    for j in unique:
        name = i + "_" + str(j)
        tmp = []
        for k in nominal_df[i]:
            if k == j:
                tmp.append(1)
            else:
                tmp.append(0)
        count +=1
        nn_df[name] = tmp
nn_df

<ipython-input-72-3de23106784c>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  nn_df[name] = tmp


DEMOGRAPHIC4_IN  DEMOGRAPHIC4_CO  DEMOGRAPHIC4_GA  DEMOGRAPHIC4_IL  \
0                   1                0                0                0   
1                   0                1                0                0   
2                   0                0                1                0   
3                   0                0                0                1   
4                   0                0                0                0   
...               ...              ...              ...              ...   
1206                0                0                0                0   
1207                0                0                0                0   
1208                0                0                0                1   
1209                0                0                0                0   
1210                0                0                0                0   

      DEMOGRAPHIC4_MS  DEMOGRAPHIC4_TX  DEMOGRAPHIC4_WA  DEMOGRAPHIC4_TN  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   0                0                0                0   
3                   0                0                0                0   
4                   1                0                0                0   
...               ...              ...              ...              ...   
1206                0                0                0                0   
1207                0                0                0                0   
1208                0                0                0                0   
1209                0                0                0                0   
1210                0                0                0                0   

      DEMOGRAPHIC4_MN  DEMOGRAPHIC4_WI  ...  DEMOGRAPHIC5_12225  \
0                   0                0  ...                   0   
1                   0                0  ...                   0   
2                   0                0  ...                   0   
3                   0                0  ...                   0   
4                   0                0  ...                   0   
...               ...              ...  ...                 ...   
1206                0                0  ...                   0   
1207                0                0  ...                   0   
1208                0                0  ...                   0   
1209                0                0  ...                   0   
1210                0                0  ...                   0   

      DEMOGRAPHIC5_31323  DEMOGRAPHIC5_90005  DEMOGRAPHIC5_18051  \
0                      0                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
...                  ...                 ...                 ...   
1206                   0                   0                   0   
1207                   0                   0                   0   
1208                   0                   0                   0   
1209                   0                   0                   0   
1210                   0                   0                   0   

      DEMOGRAPHIC5_25271  DEMOGRAPHIC5_43701  DEMOGRAPHIC5_34475  \
0                      0                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
...                  ...                 ...                 ...   
1206                   0                   1                   0   
1207          

In [73]:
selected_df = selected_df.drop(nominal_df.columns,axis=1)
for index, value in nn_df.iteritems():
    selected_df[index] = value

<ipython-input-73-02f9fd1118ec>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  selected_df[index] = value


In [156]:
selected_df.to_csv("ideology5_encoded.csv")
selected_df

HR6  MEDIA12  IDEOLOGY6  IDEOLOGY5  DEMOGRAPHIC4_IN  DEMOGRAPHIC4_CO  \
0       3        1          2          2                1                0   
1       2        1          2          0                0                1   
2       0        0          0          2                0                0   
3       2        2          3          0                0                0   
4       4        1          2          0                0                0   
...   ...      ...        ...        ...              ...              ...   
1206    3        0          1         -2                0                0   
1207    4        1          0          0                0                0   
1208    2        0          4          2                0                0   
1209    4        0          0          0                0                0   
1210    1        0          3          2                0                0   

      DEMOGRAPHIC4_GA  DEMOGRAPHIC4_IL  DEMOGRAPHIC4_MS  DEMOGRAPHIC4_TX  ...  \
0                   0                0                0                0  ...   
1                   0                0                0                0  ...   
2                   1                0                0                0  ...   
3                   0                1                0                0  ...   
4                   0                0                1                0  ...   
...               ...              ...              ...              ...  ...   
1206                0                0                0                0  ...   
1207                0                0                0                0  ...   
1208                0                1                0                0  ...   
1209                0                0                0                0  ...   
1210                0                0                0                0  ...   

      DEMOGRAPHIC5_12225  DEMOGRAPHIC5_31323  DEMOGRAPHIC5_90005  \
0                      0                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
...                  ...                 ...                 ...   
1206                   0                   0                   0   
1207                   0                   0                   0   
1208                   0                   0                   0   
1209                   0                   0                   0   
1210                   0                   0                   0   

      DEMOGRAPHIC5_18051  DEMOGRAPHIC5_25271  DEMOGRAPHIC5_43701  \
0                      0                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
...                  ...                 ...                 ...   
1206                   0                   0                   1   
1207                   0                   0                   0   
1208                   0                   0                   0   
1209                   0                   0                   0   
1210                   0                   0                   0   

      DEMOGRAPHIC5_34475  DEMOGRAPHIC5_6152  DEMOGRAPHIC5_21740  \
0                      0                  0                   0   
1                      0                  0                   0   
2                      0                  0                   0   
3                      0                  0                   0   
4                      0                  0                   0   
...                  ...                ...                 

### Modeling

In [74]:
X = selected_df.drop("IDEOLOGY5",axis=1)
y = selected_df["IDEOLOGY5"]
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = .75, test_size = .25, random_state = 72)

In [77]:
import tensorflow as tf

ANN can't take negative values so we have to convert it

In [85]:
tmp_y_train = []
values = [-2,-1,0,1,2]
encod = [[0,0,0,0,0],
        [1,0,0,0,0],
        [1,1,0,0,0],
        [1,1,1,0,0],
        [1,1,1,1,0],
        [1,1,1,1,1]]
for i in y_train:
    tmp_y_train.append(encod[values.index(i)])
tmp_y_test = []
for i in y_test:
    tmp_y_test.append(encod[values.index(i)])
tmp_y_train = np.array(tmp_y_train)
tmp_y_test = np.array(tmp_y_test)

In [150]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units = 128, activation = 'relu', input_shape = (None, 995)))

In [151]:
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units = 5, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
model.fit(x_train, tmp_y_train, epochs =5)

Epoch 1/5
29/29 [==============================] - 0s 1ms/step - loss: 3.6135 - categorical_accuracy: 0.6949
Epoch 2/5
29/29 [==============================] - 0s 1ms/step - loss: 3.3992 - categorical_accuracy: 0.8381
Epoch 3/5
29/29 [==============================] - 0s 1ms/step - loss: 3.8641 - categorical_accuracy: 0.8029
Epoch 4/5
29/29 [==============================] - 0s 1ms/step - loss: 4.7262 - categorical_accuracy: 0.7280
Epoch 5/5
29/29 [==============================] - 0s 1ms/step - loss: 5.8496 - categorical_accuracy: 0.7093


In [152]:
test_loss, test_accuracy = model.evaluate(x_test, tmp_y_test)
print(test_accuracy)

10/10 [==============================] - 0s 997us/step - loss: 5.7802 - categorical_accuracy: 0.9901
0.9900990128517151


### Testing myself because why not

HR6: Now thinking about healthcare in the country as a whole, overall, what are your impressions of the affordability of healthcare in this country?
Good 3
MEDIA12: Do you now use e-cigarettes or other electronic “vaping” products every day, some days, or not at all? 
Every day 2
DEMOGRAPHIC4: In which state are you currently residing (may be different than your permanent address)?
GA DEMOGRAPHIC4_GA = 1
DEMOGRAPHIC5: Please enter your zip or postal code of your permanent address:
DEMOGRAPHIC5_30060 = 1
IDEOLOGY6: Deeply political- highly engaged/follow politics regularly
3

In [155]:
devin = pd.DataFrame(columns = x_train.columns)
devin["HR6"] = [3]
devin["MEDIA12"] = [2]
devin["IDEOLOGY5"] = [3]
devin["DEMOGRAPHIC4_GA"] = 1
devin["DEMOGRAPHIC5_30060"] = 1
devin = devin.fillna(0)
devin = devin.drop("IDEOLOGY5",axis=1)
devin_pred = model.predict(devin)
pred = np.round(np.sum(devin_pred))
if pred == 0:
    print("Far left")
elif pred == 1:
    print("Moderate left")
elif pred == 2:
    print("Neutral")
elif pred == 3:
    print("Moderate right")
elif pred == 4:
    print("Far right")

Far right


I'd say I'm more moderate right but it's very close

In [146]:
ga = x_train.loc[x_train["DEMOGRAPHIC4_AL"] == 1]
zips = []
for index, values in ga.iteritems():
    code = index[-5:]
    if len(values.unique()) > 1 and code.isnumeric():
        zips.append(int(code))
print(zips)
zips.sort()
zips

[36535, 35206, 36207, 35984, 36420, 36541, 35243, 36856, 60478, 54869, 35603, 36350, 36111]


[35206,
 35243,
 35603,
 35984,
 36111,
 36207,
 36350,
 36420,
 36535,
 36541,
 36856,
 54869,
 60478]

In [103]:
x_train["IDEOLOGY6"].unique()

array([4, 2, 3, 0, 1], dtype=int64)